### ISSUE TITLE
dstat-plot: Type error due to parsing the first five rows as header

### ISSUE THREAD

**Issue by lauritzthamsen** [citlab/dstat-tools#12]
https://github.com/joh-mue/dstat-plot/blob/master/dstat_plot.rb#L43 at least for my CSVs only the first four rows are header rows (--> going from 1 to 4, not 0 to 4). 
the fifth row is already the category, the sixth the field. therefore, the script doesn't get valid indices for the category when the first five rows are treated as header and i'll get a type error.

is that different with your examples? i.e. do we need to make that variable?

**Comment by lauritzthamsen** [comment]
example csv:

> "Dstat 0.7.2svn CSV output"
> "Author:","Dag Wieers dag@wieers.com",,,,"URL:","http://dag.wieers.com/home-made/dstat/"
> "Host:","wally053",,,,"User:","bbdc"
> "Cmdline:","dstat --epoch --cpu -C total,0,1,2,3,4,5,6,7 --mem --net -N eth0 --disk --noheaders --nocolor --output /data/bbdc/dstat/stats.csv 1",,,,"Date:","03 Aug 2015 17:45:53 CEST"
> "epoch","total cpu usage",,,,,"cpu0 usage",,,,,"cpu1 usage",,,,,"cpu2 usage",,,,,"cpu3 usage",,,,,"cpu4 usage",,,,,"cpu5 usage",,,,,"cpu6 usage",,,,,"cpu7 usage",,,,,"memory usage",,,,"net/eth0",,"dsk/total",
> "epoch","total cpu usage:usr","total cpu usage:sys","total cpu usage:idl","total cpu usage:wai","total cpu usage:stl","cpu0 usage:usr","cpu0 usage:sys","cpu0 usage:idl","cpu0 usage:wai","cpu0 usage:stl","cpu1 usage:usr","cpu1 usage:sys","cpu1 usage:idl","cpu1 usage:wai","cpu1 usage:stl","cpu2 usage:usr","cpu2 usage:sys","cpu2 usage:idl","cpu2 usage:wai","cpu2 usage:stl","cpu3 usage:usr","cpu3 usage:sys","cpu3 usage:idl","cpu3 usage:wai","cpu3 usage:stl","cpu4 usage:usr","cpu4 usage:sys","cpu4 usage:idl","cpu4 usage:wai","cpu4 usage:stl","cpu5 usage:usr","cpu5 usage:sys","cpu5 usage:idl","cpu5 usage:wai","cpu5 usage:stl","cpu6 usage:usr","cpu6 usage:sys","cpu6 usage:idl","cpu6 usage:wai","cpu6 usage:stl","cpu7 usage:usr","cpu7 usage:sys","cpu7 usage:idl","cpu7 usage:wai","cpu7 usage:stl","used","free","buff","cach","recv","send","read","writ"
> 1438616753.302,0.226,0.017,99.742,0.015,0,0.242,0.023,99.675,0.059,0,0.248,0.018,99.713,0.021,0,0.248,0.016,99.729,0.007,0,0.250,0.017,99.727,0.006,0,0.198,0.018,99.774,0.009,0,0.203,0.015,99.776,0.006,0,0.208,0.016,99.772,0.004,0,0.211,0.016,99.769,0.004,0,16801853440,14387318784,1141649408,65441792,1138049024,20480,69414912,0,0,33629.807,30524.837
> 1438616754.303,0.125,0,99.501,0.375,0,0.990,0,96.040,2.970,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,16801853440,14386954240,1141870592,65449984,1138184192,20480,69414912,365,552,0,36864
> 1438616755.303,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,1,99,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,16801853440,14386954240,1141870592,65449984,1138184192,20480,69414912,641,2211,0,0
> 1438616756.303,0.125,0,99.875,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,0,0,100,0,0,16801853440,14386946048,1141870592,65449984,1138192384,20480,69414912,128,0,0,0

**Comment by joh-mue** [comment]
There should be an empty line between your 4th and 5th row. This is consistent with files trenner produced. I wanted to find a more dynamic way for the header evaluation anyway and I will look into that. Until then we should see why you don't have an empty 5th row.

**Comment by lauritzthamsen** [comment]
there is no empty line when statistics are recorded on wally. we use a different version of dstat there and it's also possible that dstat behaves slightly different on different hosts

**Comment by lauritzthamsen** [comment]
so, as you suggested a dynamic way would be great

**Comment by joh-mue** [comment]
![grumpy cat](http://truestorieswithgill.com/wp-content/uploads/2013/09/20130915-190532.jpg)

(okay)

**Comment by joh-mue** [comment]
fixed with PR https://github.com/citlab/dstat-tools/pull/19
