### ISSUE TITLE
dstat-plot: y-axis goes above 100 even though no line does

### ISSUE THREAD

**Issue by lauritzthamsen** [citlab/dstat-tools#13]
In some cases the plot is done with a Y axis that's 120 points high, in some cases not. This obviously makes it more difficult to compare runs.

Bad example:
![cpu_idl_5_gb_3_centers_kmeans_on_10_wallys](https://cloud.githubusercontent.com/assets/556044/9042615/2386e706-3a10-11e5-8223-d924fbbda271.png)

Good example: 
![cpu_idl_5_gb_10_centers_kmeans_on_10_wallys](https://cloud.githubusercontent.com/assets/556044/9042643/4d1093a6-3a10-11e5-99da-e64fdfb0f4be.png)

**Comment by joh-mue** [comment]
default range set to 105 unless this value is exceeded or an explicit range is set via option -y Range

fixed with PR https://github.com/citlab/dstat-tools/pull/26
