### ISSUE TITLE
DISCUSS: can we move this repository under the citlab organization

### ISSUE THREAD

**Issue by lauritzthamsen** [citlab/dstat-tools#15]
reasons:
- stored in citlab, not a personal account, so it's more visible to current and future citlab members (and also persisted there)
- organization access control, e.g. write access for our citlab team (https://github.com/orgs/citlab/teams/dataflow-resource-mngt-team - i was about to commit a fix for https://github.com/joh-mue/dstat-plot/issues/12, but didn't as i didn't think i have write access)

**Comment by lauritzthamsen** [comment]
yes, i'd like to have a repository named `dstat-tools` under the _citlab_ organization.

it should contain 
- the tools from Marcelo Veiga Neves (https://github.com/mvneves/dstat-monitor) for recording utilization statistics with dstat
- the gnu plot script from this repository,
- and scripts that analyze the recorded data, e.g. starting with https://gist.github.com/lauritzthamsen/a1eda3de579a67003d64 (i adapted the `dstat_plot.rb` script to compute the averages of a column)

**Comment by lauritzthamsen** [comment]
common features like parsing a column from csv-files can then be extracted and shared by all analysis scripts

**Comment by lauritzthamsen** [comment]
lets try to preserve all commits, branches and issues of this repository, i.e. lets actually _move it_ under the organization and then rename it

**Comment by joh-mue** [comment]
that's fine with me √

**Comment by joh-mue** [comment]
transferring a repository:

> Users must have admin or owner rights within the receiving organization before they can transfer a repository that they individually own. If the user does not already have this level of access, a temporary  admin team can be created with only the user. The user sending the repository is the only one who can  perform the transfer.
