### ISSUE TITLE
dstat-plot: Error when running the example 

### ISSUE THREAD

**Issue by lauritzthamsen** [citlab/dstat-tools#27]
running `ruby dstat_plot.rb -c "total cpu usage" -f "usr" example.csv` throws

> dstat_plot.rb:15:in `chdir': no implicit conversion of nil into String (TypeError)
>   from dstat_plot.rb:15:in`plot'
>   from dstat_plot.rb:190:in `<main>'

**Comment by joh-mue** [comment]
fixed with PR https://github.com/citlab/dstat-tools/pull/28
