### ISSUE TITLE
Scatter plot / regression line

### ISSUE THREAD

**Issue by trenner** [citlab/dstat-tools#42]
![net_total-send](https://cloud.githubusercontent.com/assets/6449765/16229982/949a7f04-37bf-11e6-8e29-23cb403aef73.png)

It would be nice to have a scatter plot / regression line instead of a line graph that connects all points. Sometimes it is nearly impossible with the current solution to see any trend in the data if the points vary a lot.

https://www.ncsu.edu/labwrite/res/gh/gh-linegraph.html

**Comment by lauritzthamsen** [comment]
I'm not really familiar with the available statistical instruments and plot types for this. I think plotting all points will still yield a lot of completely colored areas with that many workers. Maybe some form of configurable pre-aggregation of values would improve the usefulness of these graphs (think a graph that connects averages over five seconds, which should be less volatile). 
Before we implement something, we should discuss our options. @joh-mue, can you research and present some options as basis for deciding this?

**Comment by joh-mue** [comment]
will do

**Comment by trenner** [comment]
Works with:

> ```
> -s, --smoothing ALGORITHM        Smoothes the graph using the given algorithm.
> -a, --average-over SLICE_SIZE    Calculates the average for slice_size large groups of values.
> ```
