### ISSUE TITLE
y-axis limit too low

### ISSUE THREAD

**Issue by lauritzthamsen** [citlab/dstat-tools#43]
I've plots of the same job executed using different numbers of nodes and am plotting _dsk/total-read_ using the plot script (version: column_rework, 2d7fa8b6503fecc950c238e0dbb47b9ca33fbd1c). Some of the recordings are plotted with a Y-axis up to around 3e+08 (e.g. top008 below), some with only around 3e+05 (e.g. top012 below), which also look like the graphs have been cut off at that point. Is there a problem with calculating the limit of the Y-axis somewhere?

![tpchq3 flink_top008_run02__dsk_total_read](https://cloud.githubusercontent.com/assets/556044/16305192/119465ca-3959-11e6-8c78-02ff1d2d3206.png)

![tpchq3 flink_top012_run02__dsk_total_read](https://cloud.githubusercontent.com/assets/556044/16305196/16bbea64-3959-11e6-9ec6-933b63e6c98e.png)

**Comment by lauritzthamsen** [comment]
@joh-mue can you look into this?

**Comment by joh-mue** [comment]
that does look weird. I'm on it.

**Comment by joh-mue** [comment]
fixed with commit https://github.com/citlab/dstat-tools/commit/08f2d661ade31a6a777c5759db305bcd41f66e3b
